# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from khepera_communicator/SensorReadings.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SensorReadings(genpy.Message):
  _md5sum = "f0d41b6d37358788208673918228ef9d"
  _type = "khepera_communicator/SensorReadings"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 acc_x
float32 acc_y
float32 acc_z
float32 gyro_x
float32 gyro_y
float32 gyro_z
int64 pos_L
int64 pos_R
int64 spd_L
int64 spd_R
float64 time
"""
  __slots__ = ['acc_x','acc_y','acc_z','gyro_x','gyro_y','gyro_z','pos_L','pos_R','spd_L','spd_R','time']
  _slot_types = ['float32','float32','float32','float32','float32','float32','int64','int64','int64','int64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,pos_L,pos_R,spd_L,spd_R,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SensorReadings, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.acc_x is None:
        self.acc_x = 0.
      if self.acc_y is None:
        self.acc_y = 0.
      if self.acc_z is None:
        self.acc_z = 0.
      if self.gyro_x is None:
        self.gyro_x = 0.
      if self.gyro_y is None:
        self.gyro_y = 0.
      if self.gyro_z is None:
        self.gyro_z = 0.
      if self.pos_L is None:
        self.pos_L = 0
      if self.pos_R is None:
        self.pos_R = 0
      if self.spd_L is None:
        self.spd_L = 0
      if self.spd_R is None:
        self.spd_R = 0
      if self.time is None:
        self.time = 0.
    else:
      self.acc_x = 0.
      self.acc_y = 0.
      self.acc_z = 0.
      self.gyro_x = 0.
      self.gyro_y = 0.
      self.gyro_z = 0.
      self.pos_L = 0
      self.pos_R = 0
      self.spd_L = 0
      self.spd_R = 0
      self.time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f4qd().pack(_x.acc_x, _x.acc_y, _x.acc_z, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.pos_L, _x.pos_R, _x.spd_L, _x.spd_R, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.acc_x, _x.acc_y, _x.acc_z, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.pos_L, _x.pos_R, _x.spd_L, _x.spd_R, _x.time,) = _get_struct_6f4qd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f4qd().pack(_x.acc_x, _x.acc_y, _x.acc_z, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.pos_L, _x.pos_R, _x.spd_L, _x.spd_R, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.acc_x, _x.acc_y, _x.acc_z, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.pos_L, _x.pos_R, _x.spd_L, _x.spd_R, _x.time,) = _get_struct_6f4qd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f4qd = None
def _get_struct_6f4qd():
    global _struct_6f4qd
    if _struct_6f4qd is None:
        _struct_6f4qd = struct.Struct("<6f4qd")
    return _struct_6f4qd
