// Generated by gencpp from file robosar_controller/RobosarControllerFeedback.msg
// DO NOT EDIT!


#ifndef ROBOSAR_CONTROLLER_MESSAGE_ROBOSARCONTROLLERFEEDBACK_H
#define ROBOSAR_CONTROLLER_MESSAGE_ROBOSARCONTROLLERFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseWithCovariance.h>

namespace robosar_controller
{
template <class ContainerAllocator>
struct RobosarControllerFeedback_
{
  typedef RobosarControllerFeedback_<ContainerAllocator> Type;

  RobosarControllerFeedback_()
    : pose()  {
    }
  RobosarControllerFeedback_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct RobosarControllerFeedback_

typedef ::robosar_controller::RobosarControllerFeedback_<std::allocator<void> > RobosarControllerFeedback;

typedef boost::shared_ptr< ::robosar_controller::RobosarControllerFeedback > RobosarControllerFeedbackPtr;
typedef boost::shared_ptr< ::robosar_controller::RobosarControllerFeedback const> RobosarControllerFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator1> & lhs, const ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator1> & lhs, const ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robosar_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47ee8cafbfba31d9f2b33076c5078c94";
  }

  static const char* value(const ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47ee8cafbfba31d9ULL;
  static const uint64_t static_value2 = 0xf2b33076c5078c94ULL;
};

template<class ContainerAllocator>
struct DataType< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robosar_controller/RobosarControllerFeedback";
  }

  static const char* value(const ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"geometry_msgs/PoseWithCovariance pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobosarControllerFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robosar_controller::RobosarControllerFeedback_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSAR_CONTROLLER_MESSAGE_ROBOSARCONTROLLERFEEDBACK_H
