// Generated by gencpp from file robosar_messages/agent_status.msg
// DO NOT EDIT!


#ifndef ROBOSAR_MESSAGES_MESSAGE_AGENT_STATUS_H
#define ROBOSAR_MESSAGES_MESSAGE_AGENT_STATUS_H

#include <ros/service_traits.h>


#include <robosar_messages/agent_statusRequest.h>
#include <robosar_messages/agent_statusResponse.h>


namespace robosar_messages
{

struct agent_status
{

typedef agent_statusRequest Request;
typedef agent_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct agent_status
} // namespace robosar_messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robosar_messages::agent_status > {
  static const char* value()
  {
    return "8e11fd7ffef74f85ca9b7e06e813c80a";
  }

  static const char* value(const ::robosar_messages::agent_status&) { return value(); }
};

template<>
struct DataType< ::robosar_messages::agent_status > {
  static const char* value()
  {
    return "robosar_messages/agent_status";
  }

  static const char* value(const ::robosar_messages::agent_status&) { return value(); }
};


// service_traits::MD5Sum< ::robosar_messages::agent_statusRequest> should match
// service_traits::MD5Sum< ::robosar_messages::agent_status >
template<>
struct MD5Sum< ::robosar_messages::agent_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robosar_messages::agent_status >::value();
  }
  static const char* value(const ::robosar_messages::agent_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robosar_messages::agent_statusRequest> should match
// service_traits::DataType< ::robosar_messages::agent_status >
template<>
struct DataType< ::robosar_messages::agent_statusRequest>
{
  static const char* value()
  {
    return DataType< ::robosar_messages::agent_status >::value();
  }
  static const char* value(const ::robosar_messages::agent_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robosar_messages::agent_statusResponse> should match
// service_traits::MD5Sum< ::robosar_messages::agent_status >
template<>
struct MD5Sum< ::robosar_messages::agent_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robosar_messages::agent_status >::value();
  }
  static const char* value(const ::robosar_messages::agent_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robosar_messages::agent_statusResponse> should match
// service_traits::DataType< ::robosar_messages::agent_status >
template<>
struct DataType< ::robosar_messages::agent_statusResponse>
{
  static const char* value()
  {
    return DataType< ::robosar_messages::agent_status >::value();
  }
  static const char* value(const ::robosar_messages::agent_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOSAR_MESSAGES_MESSAGE_AGENT_STATUS_H
