// Generated by gencpp from file robosar_messages/sys_odom_resetRequest.msg
// DO NOT EDIT!


#ifndef ROBOSAR_MESSAGES_MESSAGE_SYS_ODOM_RESETREQUEST_H
#define ROBOSAR_MESSAGES_MESSAGE_SYS_ODOM_RESETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robosar_messages
{
template <class ContainerAllocator>
struct sys_odom_resetRequest_
{
  typedef sys_odom_resetRequest_<ContainerAllocator> Type;

  sys_odom_resetRequest_()
    {
    }
  sys_odom_resetRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sys_odom_resetRequest_

typedef ::robosar_messages::sys_odom_resetRequest_<std::allocator<void> > sys_odom_resetRequest;

typedef boost::shared_ptr< ::robosar_messages::sys_odom_resetRequest > sys_odom_resetRequestPtr;
typedef boost::shared_ptr< ::robosar_messages::sys_odom_resetRequest const> sys_odom_resetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace robosar_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robosar_messages/sys_odom_resetRequest";
  }

  static const char* value(const ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sys_odom_resetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::robosar_messages::sys_odom_resetRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSAR_MESSAGES_MESSAGE_SYS_ODOM_RESETREQUEST_H
