// Generated by gencpp from file robosar_messages/taskgen_getwayptsRequest.msg
// DO NOT EDIT!


#ifndef ROBOSAR_MESSAGES_MESSAGE_TASKGEN_GETWAYPTSREQUEST_H
#define ROBOSAR_MESSAGES_MESSAGE_TASKGEN_GETWAYPTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/OccupancyGrid.h>

namespace robosar_messages
{
template <class ContainerAllocator>
struct taskgen_getwayptsRequest_
{
  typedef taskgen_getwayptsRequest_<ContainerAllocator> Type;

  taskgen_getwayptsRequest_()
    : map()
    , threshold(0.0)
    , iterations(0)  {
    }
  taskgen_getwayptsRequest_(const ContainerAllocator& _alloc)
    : map(_alloc)
    , threshold(0.0)
    , iterations(0)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _map_type;
  _map_type map;

   typedef double _threshold_type;
  _threshold_type threshold;

   typedef int64_t _iterations_type;
  _iterations_type iterations;





  typedef boost::shared_ptr< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct taskgen_getwayptsRequest_

typedef ::robosar_messages::taskgen_getwayptsRequest_<std::allocator<void> > taskgen_getwayptsRequest;

typedef boost::shared_ptr< ::robosar_messages::taskgen_getwayptsRequest > taskgen_getwayptsRequestPtr;
typedef boost::shared_ptr< ::robosar_messages::taskgen_getwayptsRequest const> taskgen_getwayptsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator1> & lhs, const ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.map == rhs.map &&
    lhs.threshold == rhs.threshold &&
    lhs.iterations == rhs.iterations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator1> & lhs, const ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robosar_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03d18fe5126a914ee71fdd8a78836825";
  }

  static const char* value(const ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03d18fe5126a914eULL;
  static const uint64_t static_value2 = 0xe71fdd8a78836825ULL;
};

template<class ContainerAllocator>
struct DataType< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robosar_messages/taskgen_getwayptsRequest";
  }

  static const char* value(const ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/OccupancyGrid map\n"
"float64 threshold\n"
"int64 iterations\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/OccupancyGrid\n"
"# This represents a 2-D grid map, in which each cell represents the probability of\n"
"# occupancy.\n"
"\n"
"Header header \n"
"\n"
"#MetaData for the map\n"
"MapMetaData info\n"
"\n"
"# The map data, in row-major order, starting with (0,0).  Occupancy\n"
"# probabilities are in the range [0,100].  Unknown is -1.\n"
"int8[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/MapMetaData\n"
"# This hold basic information about the characterists of the OccupancyGrid\n"
"\n"
"# The time at which the map was loaded\n"
"time map_load_time\n"
"# The map resolution [m/cell]\n"
"float32 resolution\n"
"# Map width [cells]\n"
"uint32 width\n"
"# Map height [cells]\n"
"uint32 height\n"
"# The origin of the map [m, m, rad].  This is the real-world pose of the\n"
"# cell (0,0) in the map.\n"
"geometry_msgs/Pose origin\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map);
      stream.next(m.threshold);
      stream.next(m.iterations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct taskgen_getwayptsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robosar_messages::taskgen_getwayptsRequest_<ContainerAllocator>& v)
  {
    s << indent << "map: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.map);
    s << indent << "threshold: ";
    Printer<double>::stream(s, indent + "  ", v.threshold);
    s << indent << "iterations: ";
    Printer<int64_t>::stream(s, indent + "  ", v.iterations);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSAR_MESSAGES_MESSAGE_TASKGEN_GETWAYPTSREQUEST_H
