; Auto-generated. Do not edit!


(cl:in-package robosar_controller-msg)


;//! \htmlinclude RobosarControllerGoal.msg.html

(cl:defclass <RobosarControllerGoal> (roslisp-msg-protocol:ros-message)
  ((agent_name
    :reader agent_name
    :initarg :agent_name
    :type cl:string
    :initform "")
   (path
    :reader path
    :initarg :path
    :type nav_msgs-msg:Path
    :initform (cl:make-instance 'nav_msgs-msg:Path)))
)

(cl:defclass RobosarControllerGoal (<RobosarControllerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RobosarControllerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RobosarControllerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robosar_controller-msg:<RobosarControllerGoal> is deprecated: use robosar_controller-msg:RobosarControllerGoal instead.")))

(cl:ensure-generic-function 'agent_name-val :lambda-list '(m))
(cl:defmethod agent_name-val ((m <RobosarControllerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robosar_controller-msg:agent_name-val is deprecated.  Use robosar_controller-msg:agent_name instead.")
  (agent_name m))

(cl:ensure-generic-function 'path-val :lambda-list '(m))
(cl:defmethod path-val ((m <RobosarControllerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robosar_controller-msg:path-val is deprecated.  Use robosar_controller-msg:path instead.")
  (path m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RobosarControllerGoal>) ostream)
  "Serializes a message object of type '<RobosarControllerGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'agent_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'agent_name))
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'path) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RobosarControllerGoal>) istream)
  "Deserializes a message object of type '<RobosarControllerGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'agent_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'agent_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'path) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RobosarControllerGoal>)))
  "Returns string type for a message object of type '<RobosarControllerGoal>"
  "robosar_controller/RobosarControllerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RobosarControllerGoal)))
  "Returns string type for a message object of type 'RobosarControllerGoal"
  "robosar_controller/RobosarControllerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RobosarControllerGoal>)))
  "Returns md5sum for a message object of type '<RobosarControllerGoal>"
  "2d764ee62a71f032665047c211608c2e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RobosarControllerGoal)))
  "Returns md5sum for a message object of type 'RobosarControllerGoal"
  "2d764ee62a71f032665047c211608c2e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RobosarControllerGoal>)))
  "Returns full string definition for message of type '<RobosarControllerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string agent_name~%nav_msgs/Path path~%~%================================================================================~%MSG: nav_msgs/Path~%#An array of poses that represents a Path for a robot to follow~%Header header~%geometry_msgs/PoseStamped[] poses~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RobosarControllerGoal)))
  "Returns full string definition for message of type 'RobosarControllerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string agent_name~%nav_msgs/Path path~%~%================================================================================~%MSG: nav_msgs/Path~%#An array of poses that represents a Path for a robot to follow~%Header header~%geometry_msgs/PoseStamped[] poses~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RobosarControllerGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'agent_name))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'path))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RobosarControllerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RobosarControllerGoal
    (cl:cons ':agent_name (agent_name msg))
    (cl:cons ':path (path msg))
))
